_BASE_: "./base.yaml"
RUN_N_TIMES: 999
DATA:
  NAME: "nabirds"
  DATAPATH: ""  #TODO: need to specify here
  NUMBER_CLASSES: 555
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01