_BASE_: "./base.yaml"
RUN_N_TIMES: 999999999999
DATA:
  # NAME: "vtab-cifar(num_classes=100)"
  # NAME: "vtab-eurosat"
  # NAME: "vtab-oxford_flowers102"
  # NAME: "vtab-caltech101"
  # NAME: "vtab-clevr(task=\"closest_object_distance\")"
  # NAME: "vtab-clevr(task=\"count_all\")"
  # NAME: "vtab-dtd"
  # NAME: "vtab-oxford_iiit_pet"
  # NAME: "vtab-patch_camelyon"
  # NAME: "vtab-sun397"
  # NAME: "vtab-dmlab"
  # NAME: "vtab-svhn"
  # NAME: "vtab-smallnorb(predicted_attribute=\"label_azimuth\")"
  # NAME: "vtab-smallnorb(predicted_attribute=\"label_elevation\")"
  # NAME: "vtab-dsprites(predicted_attribute=\"label_x_position\",num_classes=16)"
  # NAME: "vtab-dsprites(predicted_attribute=\"label_orientation\",num_classes=16)"
  # NAME: "vtab-kitti(task=\"closest_vehicle_distance\")"
  NAME: "vtab-diabetic_retinopathy(config=\"btgraham-300\")"
  DATAPATH: "/shared/catherine_gai/vtab"  #TODO: need to specify here
  NUMBER_CLASSES: 5
  MULTILABEL: False
MODEL:
  # vit base bottom-up
  MODEL_ROOT: "/shared/bfshi/projects/Robust-Vision-Transformer/output/vit-base/ImageNet_221002_1516/checkpoint.pth"
  TYPE: "vit_top_down"
  TRANSFER_TYPE: "prompt"
  PROMPT:
    DEEP: "True"
    NUM_TOKENS: 100
    DROPOUT: 0.1
  SAVE_MODEL_CKPT: True
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
  TOTAL_EPOCH: 100
OUTPUT_DIR: "/shared/catherine_gai/vpt_training/bottomup_class_alt/vit_base"