#### models path dirs
focal_alpha: 0.5
network_arch: resnet_token_attention_plugin #convnextv1 #shunt_convnext, conformer, efficient

# history of checkpoints: note they might not exist any more

## best performance: 0.967 0.759
## robust: Epoch2_105999_ViT 0.708
## non-robust tencent: resnet_token_attention_plugin/954775_12_ViT

model_load_number: resnet_token_attention_plugin/954775_12_ViT
#### general settings
conduct_train: true
conduct_test: true
test_save_checkpoint: true

train_dataset: megvii
test_dataset: tencent
with_data_aug: true

gpu_ids: [2]
operations_list: ['none','single','dual','three','four']
test_operation_list: ['single','dual','three','four']
task_name: resnet_token_attention_plugin

restart_step: 1000
model_save_period: 2000

with_dual_process: false

datasets:
  train:
    name: Rerun
    mode: LQGT
#    dataroot_GT: /qichaoying/Downloads/Invertible-Image-Rescaling-master/icassp_real/images    # Test images
#    dataroot_GT: /groupshare//Places/data_256                                        # Places
#    dataroot_GT: /groupshare/CelebA/img/img_celeba_200                                          # CelebA
#    dataroot_GT: /groupshare/paris_street_view/paris_train                            # ParisStreetView
    dataroot_GT: /groupshare/ISP_results/xxhu_test/UNet/FORGERY_0                                   # COCO
#    dataroot_GT: /groupshare//Flickr1024/train                                 # Flicker
#    dataroot_GT: /groupshare//DIV2K_valid                                # DIV2K
#    dataroot_GT: /groupshare//VOC2012/JPEGImages
#    dataroot_GT: /groupshare//UCID_color/images                                                 # UCID
#    dataroot_GT: /groupshare//ILSVRC2012_img_val                                      # ImageNet
    dataroot_LQ: /groupshare/ISP_results/xxhu_test/UNet/MASK

    use_shuffle: true
    n_workers: 2 # per GPU

    batch_size: 8 # 32 for hierarchical
    GT_size: 512 # 608

    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /groupshare/ISP_results/xxhu_test/UNet/FORGERY_0
    dataroot_LQ: /groupshare/ISP_results/xxhu_test/UNet/MASK # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    GT_size: 512


train:
  lr_CNN: !!float 1e-4
  lr_transformer: !!float 5e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
